import assign from 'lodash/assign';

let defaultConfig = {
  debugMode: true,
};

if (process.env.NODE_ENV === 'development') {
  defaultConfig = {
    indexHost: '',
    adminAjax: {
      url: '',
      nonce: '',
    },
    debugMode: true,
    query: {
      initialQuery: '',
      postType: '',
      filters: {
        // postType: [],
      },
      sort: false,
      sortDirection: 'asc',
    },
    postTypeLabels: {
      page: { name: 'Pages', singular_name: 'Page' },
      post: { name: 'Posts', singular_name: 'Post' },
      aa_book: { name: 'Books', singular_name: 'Book' },
      aa_community_groups: { name: 'Community Groups', singular_name: 'Community Group' },
      aa_event_session: { name: 'Event Sessions', singular_name: 'Event Session' },
      aa_experience_report: { name: 'Experience Reports', singular_name: 'Experience Report' },
      aa_glossary: { name: 'Glossary Terms', singular_name: 'Glossary Term' },
      aa_initiative: { name: 'Initiatives', singular_name: 'Initiative' },
      aa_organizations: { name: 'Organizations', singular_name: 'Organization' },
      aa_research_paper: { name: 'Research Papers', singular_name: 'Research Paper' },
      aa_story: { name: 'News & Press', singular_name: 'News & Press' },
      aa_video: { name: 'Videos', singular_name: 'Video' },
      aa_podcast: { name: 'Podcasts', singular_name: 'Podcast' },
      'third-party-event': { name: 'Third Party Event', singular_name: 'Third Party Event' },
    },
    taxonomies: {
      categories: {
        label: 'Categories',
        terms: [
          'AA Sponsored',
          'Business',
          'Commercial',
          'Community',
          'Framework',
          'Mindset',
          'Non-Commercial',
          'People',
          'Process',
          'Technology',
          'The Alliance',
          'Uncategorized',
        ],
      },
      tags: {
        label: 'Tags',
        terms: [
          '2017',
          'acceptance test',
          'agile',
          'Agile Alliance Mission',
          'agile at scale',
          'agile development',
          'agile management',
          'agile manifesto',
          'agile metrics',
          'agile retrospectives',
          'agile teams',
          'antipattern',
          'atdd',
          'automated build',
          'backlog',
          'backlog refinement',
          'bdd',
          'board of directors',
          'build measure learn',
          'burndown chart',
          'burnup chart',
          'co-location',
          'collective ownership',
          'Community Group',
          'conference',
          'continuous deployment',
          'continuous integration',
          'continuous learning',
          'crc card',
          'current',
          'daily meeting',
          'definition of done',
          'devops',
          'enterprise agile',
          'estimation',
          'events',
          'executive',
          'extreme programming',
          'kanban',
          'keynote',
          'lightning talks',
          'Meetup',
          'mob programming',
          'mvp',
          'pair programming',
          'past',
          'planning poker',
          'product owner',
          'product ownership',
          'relative estimation',
          'retrospectives',
          'scrum',
          'scrum master',
          'scrumban',
          'staff',
          'story mapping',
          'subscriber class',
          'tdd',
          'team',
          'technical debt',
          'the alliance',
          'three amigos',
          'timebox',
          'user experience',
          'User Group',
          'user stories',
          'ux',
          'values and principles',
          'women',
          'women in agile',
          'women in technology',
          'xp',
        ],
      },
      sources: {
        label: 'Sources',
        terms: [
          'Agile Alliance Technical Conference 2016',
          'Agile Alliance Technical Conference 2017',
          'Agile Brazil',
          'Agile Engineering',
          'Agile Executive Forum 2013',
          'Agile Executive Forum 2015',
          'Agile Executive Forum 2016',
          'Agile Practice Guide',
          'Agile Product Management',
          'Agile2010',
          'Agile2011',
          'Agile2012',
          'Agile2013',
          'Agile2014',
          'Agile2015',
          'Agile2016',
          'Agile2017',
          'AgileEurope2016',
          'Event',
          'Experience Report',
          'Initiatives',
          'Member Submitted',
          'OnAgile2015',
          'OnAgile2016',
          'Supporting Agile Adoption',
          'Technical Debt',
          'Women in Agile',
        ],
      },
      communityGroupLocations: {
        label: 'Locations',
        terms: [
          'Africa',
          'Albany',
          'Alberta',
          'Algiers',
          'Appleton',
          'Argentina',
          'Arizona',
          'Asia',
          'Atlanta',
          'Auckland',
          'Augsburg',
          'Austin',
          'Australia',
          'B.C.',
          'Bahia',
          'Bangalore',
          'Bangladesh',
          'Baton Rouge',
          'Bay Area',
          'Belgium',
          'Belo Horizonte',
          'Bengaluru',
          'Bentonville',
          'Blacksburg',
          'Bogotá',
          'Boise',
          'Bolivia',
          'Bonn',
          'Bosnia',
          'Boston',
          'Boulder',
          'Brazil',
          'Brighton',
          'Brisbane',
          'Budapest',
          'Buenos Aires',
          'Calgary',
          'Cali',
          'California',
          'Canada',
          'Cape Town',
          'Cardiff',
          'Carmel',
          'Central America',
          'Charleston',
          'Charlotte',
          'Charlottesville',
          'Chile',
          'China',
          'Cincinnati',
          'Cleveland',
          'Colombia',
          'Colombo',
          'Colorado',
          'Columbus',
          'Connecticut',
          'Copenhagen',
          'Costa Rica',
          'Czech Republic',
          'Da Nang',
          'Dallas-Forth Worth',
          'Denmark',
          'Denver',
          'Des Moines',
          'Dublin',
          'Düsseldorf',
          'East Lansing',
          'Edinburgh',
          'Edmonton',
          'Europe',
          'Finland',
          'Florida',
          'France',
          'Gainesville',
          'Georgia',
          'Germany',
          'Grand Rapids',
          'Grenoble',
          'Halifax',
          'Hamburg',
          'Hartford',
          'Hong Kong',
          'Houston',
          'Hudson',
          'Hungary',
          'Hyderabad',
          'Iceland',
          'Idaho',
          'Illinois',
          'India',
          'Indiana',
          'Indonesia',
          'Iowa',
          'Iran',
          'Ireland',
          'Israel',
          'Italy',
          'Jacksonville',
          'Japan',
          'Johannesburg',
          'Kansas City',
          'Karlsruhe',
          'Knoxville',
          'Kraków',
          'Latvia',
          'Lebanon',
          'Lincoln',
          'Lithuania',
          'Liverpool',
          'London',
          'Los Angeles',
          'Louisiana',
          'Luxembourg',
          'Madrid',
          'Maine',
          'Malaysia',
          'Manchester',
          'Manitoba',
          'Maryland',
          'Massachusetts',
          'Melbourne',
          'Memphis',
          'Miami',
          'Michigan',
          'Milwaukee',
          'Minneapolis',
          'Minnesota',
          'Missouri',
          'Montana',
          'Montréal',
          'Morocco',
          'Munich',
          'Nashville',
          'Nebraska',
          'Netherlands',
          'New Jersey',
          'New Orleans',
          'New South Wales',
          'New York',
          'New York',
          'New Zealand',
          'Newcastle Upon Tyne',
          'Normal',
          'North America',
          'North Carolina',
          'Norway',
          'Nova Scotia',
          'Oceania',
          'Ohio',
          'Oklahoma',
          'Omaha',
          'Ontario',
          'Oregon',
          'Orlando',
          'Oslo',
          'Ottawa',
          'Øresund',
          'Pakistan',
          'Paris',
          'Pennsylvania',
          'Philadelphia',
          'Phoenix',
          'Pittsburgh',
          'Pleasanton',
          'Poland',
          'Portland',
          'Portland',
          'Porto de Galinhas',
          'Portugal',
          'Prague',
          'Provo',
          'Puerto Rico',
          'Pune',
          'Quebec',
          'Quebec City',
          'Queensland',
          'Raleigh',
          'Reykjavík',
          'Richmond',
          'Rio de Janeiro',
          'Rio Grande do Sul',
          'Romania',
          'Russia',
          'Salt Lake City',
          'San Diego',
          'San Francisco',
          'San Juan',
          'Santa Barbara',
          'Sarajevo',
          'Saudi Arabia',
          'Saudi Arabia',
          'Scotland',
          'Seattle',
          'Serbia',
          'Singapore',
          'South Africa',
          'South America',
          'South Carolina',
          'South Korea',
          'Spain',
          'Sri Lanka',
          'St. Louis',
          'State College',
          'Stockholm',
          'Stuttgart',
          'Sweden',
          'Switzerland',
          'Sydney',
          'Taiwan',
          'Tampa',
          'Tennessee',
          'Texas',
          'Thailand',
          'Toronto',
          'Toulouse',
          'Trondheim',
          'Tucson',
          'Tulsa',
          'Tunisia',
          'Twin Cities',
          'Ukraine',
          'United Arab Emirates',
          'United Kingdom',
          'Uruguay',
          'USA',
          'Utah',
          'Utrecht',
          'Vancouver',
          'Venezuela',
          'Victoria',
          'Victoria',
          'Vietnam',
          'Virginia',
          'Washington',
          'Washington D.C.',
          'Waterloo',
          'West Yorkshire',
          'Winnipeg',
          'Wisconsin',
        ],
      },
      eventSessionTracks: {
        label: 'Event Session Tracks',
        terms: [
          'Agile Bootcamp',
          'Audacious Salon',
          'Coaching &amp; Mentoring',
          'Collaboration Culture &amp; Teams',
          'Crowdsourced',
          'Development Practices &amp; Craftsmanship',
          'DevOps',
          'Enterprise Agile',
          'Evening Events',
          'Executive Forum Session',
          'Experience Reports',
          'Experience Stage',
          'Government',
          'Individual and Organizational Change',
          'Keynote',
          'Knowledge and Education',
          'Leadership',
          'Learning',
          'Lightning Talks',
          'Main Stage',
          'Project Program and Portfolio Management',
          'Research',
          'Sessions',
          'Special Events',
          'Stalwarts',
          'Technical Excellence',
          'Testing &amp; Quality',
          'The Future of Agile Software Development (IEEE Software)',
          'User Experience',
          'Value Creation',
          'Working with Customers',
        ],
      },
      eventSessionAudienceLevels: {
        label: 'Audience Levels',
        terms: [
          'Advancing',
          'Learning',
          'Practicing',
        ],
      },
      eventSessionTypes: {
        label: 'Session Types',
        terms: [
          'Keynote',
          'Talk',
          'Workshop',
        ],
      },
      eventSessionKeywords: {
        label: 'Event Session Keywords',
        terms: [
          'Agile2015',
        ],
      },
      experienceReportCategories: {
        label: 'Experience Report Categories',
        terms: [
          'Agile Adaptation',
          'Agile Adoption',
          'Agile Architects',
          'Agile Company',
          'Agile in Healthcare',
          'Agile Marketing',
          'Agile Outside of Software',
          'Agile Sales',
          'Agile Transformation',
          'Automation',
          'Business Intelligence',
          'Coaching',
          'Code Jams',
          'Communities of Practice',
          'DevOps',
          'Distributed Teams',
          'Engineering Management',
          'Estimation',
          'Exploratory Testing',
          'Facilitation',
          'Flow Metrics',
          'Gamification',
          'Government',
          'Kanban',
          'Large Scale Agile',
          'Mission Critical Systems',
          'Mob Programming',
          'Operations',
          'Portfolio Management',
          'Process Improvement',
          'Product Development',
          'QA',
          'Scaling Agile',
          'Scrum',
          'Six Sigma',
          'TDD',
          'Team Building Practices',
          'Team Improvement',
          'Team Practices',
          'Teams',
          'Testing',
          'User Groups',
        ],
      },
      organizationCategories: {
        label: 'Organizations Categories',
        terms: [],
      },
      status: {
        label: 'Organization Status',
        terms: [
          'Active',
        ],
      },
      storyCategories: {
        label: 'Story Categories',
        terms: [
          '2008',
          '2009',
          '2010',
          '2011',
          '2012',
          '2013',
          '2014',
          '2015',
          '2016',
          '2017',
          'Agile Alliance',
          'agile2016',
          'agile2017',
          'events',
        ],
      },
      videoTypes: {
        label: 'Video Types',
        terms: [
          'Industry Panel',
          'Initiative Video',
          'Keynote Video',
          'Learning Video',
          'Lightning Talk Video',
          'Podcasts',
          'Session Video',
        ],
      },
      videoAudienceLevels: {
        label: 'Audience Levels',
        terms: [
          'Advancing',
          'Learning',
          'Practicing',
        ],
      },
      podcastTypes: {
        label: 'Podcast Types',
        terms: [
          'Podcasts',
          'Interviews',
          'Radioshow',
        ],
      },
      permissionLevel: {
        label: 'Membership Level',
        terms: [
          'Public',
          'Subscriber',
          'Member',
        ],
      },
    },
    ui: {
      displayTextSearch: true,
      filters: [],
    },
  };
  try {
    /* eslint-disable global-require */
    const localConfig = require('@/local-config');
    defaultConfig = assign({}, defaultConfig, localConfig);
  } catch (E) {
    // No local config found. Check out `local-config.sample.js` for more.
  }
}

export default assign({}, defaultConfig, window.aaSearch);
